### ISSUE TITLE
Nova Prospekt guards always have the "None Standard Issue"/random weapon option applied to them

### ISSUE THREAD

**Issue by Flrys** [Milkman68/HL2-RebalanceMod#3]
They always have a chance to randomly spawn with revolvers/pistols even if this option is off.

**Comment by Milkman68** [comment]
I'm going to close this, as this is intentional. The Prisonguards Ar2's and Shotgun's are replaced with lower-ranking weapons like Pistol's and Revolver's by default. I made it this way to make both Soldiers and Prisongaurds more distinct gameplay-wise, instead of their only difference being visual.

And it also adds more gameplay variety overall, as you're not fighting the same soldiers with the same weapons for the entire game.
